### ISSUE TITLE
Clear WorldMarkers does not work in German version of WoW

### ISSUE THREAD

**Issue by michaelvolz** [cr4ckp0t/ElvUI_RaidMarkers#11]
The command `/cwm all` seems to be defective in the localized version of WoW (9.0.2.36753 Shadowlands). 
The workaround is to use the number zero as replacement for `all`.

`/cwm 0`

This should work in all languages. It worked on our machine, though xD.

**Comment by cr4ckp0t** [comment]
I made the change in 6.0.3.
