### ISSUE TITLE
Addon Phrase for Germany

### ISSUE THREAD

**Issue by Rafa28062013** [cr4ckp0t/ElvUI_RaidMarkers#15]
Hello,

were i can find the Addon Phrase for my locale? Im from Germany. The Link on Cruseforge/WoW Up dont work.

**Comment by Rafa28062013** [comment]
Verstehst du Deutsch? :) Hab das Problem und finde das Addon nicht in Elvui.

**Comment by Rafa28062013** [comment]
Brauch ich da irgendwas das es bei mir Funktioniert? Es steht etwas in der Beschreibung, aber die Links funktionieren nicht

**Comment by cr4ckp0t** [comment]
Is https://www.curseforge.com/wow/addons/elvui-raid-markers/localization what you're looking for?
