### ISSUE TITLE
Bar stopped working with pre-patch

### ISSUE THREAD

**Issue by bchevreau** [cr4ckp0t/ElvUI_RaidMarkers#18]
The bar seems to not work anymore with Dragonflight pre-patch. I assume it has to do with the same issue that a lot of "clicking" functionalities in the game have been having, but none of the markers or floor/flare markers work when clicking.

**Comment by ywi** [comment]
True its not working. Elvui has been updated though

**Comment by DarthPredator** [comment]
In this case ElvUI has nothing to do with it, blizz changed how casting on press/release works on the backend.
Anyways, have the fix in attachments
[ElvUI_RaidMarkers.zip](https://github.com/cr4ckp0t/ElvUI_RaidMarkers/files/9946687/ElvUI_RaidMarkers.zip)

**Comment by teegles** [comment]
Thanks @DarthPredator that did fix target markers but not raid markers. Any ideas or is this a known issue still? 

Appreciate your work :)

**Comment by DarthPredator** [comment]
@teegles Sorry for a late reply, irl and stuff.

I can try and see if those work for me. Currently my own bar works just fine for both marks and flares with the exact same changes I made in the archive. So I assume there is something else we might be missing cause I saw at least one other person mentioning my bar not working with flares for them. 

If you could play around with settings, cvars and all that to try and get it to work, it could help. Also just to be sure, keep in mind the markers you put on the ground (flares) are only for group situations, you can't place them when solo or not group leader/assist as far as I'm aware.

**Comment by teegles** [comment]
It does appear to be working in group content. I wasn't aware of the limitation of needing to be in a group with lead/assist. I know it wasn't working before the fixed version above but is indeed now working. Thank you for your work!

**Comment by cr4ckp0t** [comment]
I merged a Pull request into the code to fix this issue, and others related to the CVar changes introduced in pre-patch.
