### ISSUE TITLE
World Markers not working in 8.3

### ISSUE THREAD

**Issue by rayfoxii** [cr4ckp0t/ElvUI_RaidMarkers#2]
Thanks for the addon, I've been using it a lot but 8.3 seems to have broken world markers on all addons that place them.

**Comment by wald80** [comment]
Can confirm above with same issue. When logging into Wow (BFA, not Classic) I am greeted by wonderful LUA Errors, all which start the same as "Missing Entry for..." (missing star, circle, diamond, triangle, moon. square, red-X & skull plus the "Remove Marker" error too, including at the bottom). 

Elvui; 11.41
Shadow & Light 3.74
Elvui Raid Markers; 5.2.0
Wow Info; 8.3.0

```
Message: AceLocale-3.0: ElvUI_RaidMarkers: Missing entry for 'Star'
Time: Mon May 18 10:52:03 2020
Count: 1
Stack: AceLocale-3.0: ElvUI_RaidMarkers: Missing entry for 'Star'
[string "@Interface\AddOns\ElvUI_RaidMarkers\Datatext.lua"]:24: in main chunk

Locals: <none>

Message: AceLocale-3.0-6: ElvUI_RaidMarkers: Missing entry for 'Star'
Time: Sun May 17 00:03:59 2020
Count: 1
Stack: AceLocale-3.0-6: ElvUI_RaidMarkers: Missing entry for 'Star'

Locals: <none>
```
