### ISSUE TITLE
Custom script warning

### ISSUE THREAD

**Issue by brandor5** [cr4ckp0t/ElvUI_RaidMarkers#20]
I've noticed since dragonflight came out that I'm getting a custom script warning when trying to use this addon. The specific error is:

"You are attempting to run a custom script. Running scripts could compromise your character causing the loss of items or gold. Allow custom scripts?"

Sounds pretty scary.

I've tried reinstalling and renaming WTF folder to clear out old settings. Still getting the error.

Let me know if there is any info you need.

**Comment by cr4ckp0t** [comment]
It is because the addon has to use macros to set the world markers. There is no other way to use the functionality.

The code is completely open source, feel free to look it over or have someone else audit it.
