### ISSUE TITLE
get this error with last update

### ISSUE THREAD

**Issue by airstevo** [cr4ckp0t/ElvUI_RaidMarkers#3]
Message: AceLocale-3.0: ElvUI_RaidMarkers: Missing entry for 'Plugins by Crackpotx'
Time: Tue May 19 22:46:41 2020
Count: 1
Stack: AceLocale-3.0: ElvUI_RaidMarkers: Missing entry for 'Plugins by Crackpotx'
[string "@Interface\AddOns\DataStore\libs\AceLocale-3.0\AceLocale-3.0.lua"]:31: in function <...ddOns\DataStore\libs\AceLocale-3.0\AceLocale-3.0.lua:29>
[string "@Interface\AddOns\ElvUI_RaidMarkers\ElvUI_RaidMarkers.lua"]:240: in function `callback'
[string "@Interface\AddOns\ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua"]:164: in function <...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:158>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\Config.lua"]:1067: in function `ToggleOptionsUI'
[string "@Interface\AddOns\ElvUI\init.lua"]:206: in function <Interface\AddOns\ElvUI\init.lua:206>

Locals: <none>

**Comment by cr4ckp0t** [comment]
Fixed in 5.2.1. Sorry about that.
