### ISSUE TITLE
ELVUI_RaidMarkers Remove unsupported addons from twitch

### ISSUE THREAD

**Issue by thenuclear1** [cr4ckp0t/ElvUI_RaidMarkers#6]
Twitch needs to have a function to remove unsupported addons from its' list of available addons when they are no longer being supported. Yes people can uninstall the addons themselves but a better solution is for twitch to remove unsupported addons after one week of no replies to current issues with an addon which would help others from downloading a broken addon that is not being updated/ supported. 
https://www.curseforge.com/wow/addons/elvui-raid-markers
is one of those addons that needs a faster method of being removed from available downloads since it obviously is not being supported since someone uploaded an update for it on 13MAy2020 but never responded to any of the errors with the addon.
An easy solution would be for Twitch to remove an addon after eiher1-2 weeks of an addon not being responded to that and is having issues so people would not even see it as an option for download and thereby keeping many from getting a broken addon in the first place.

**Comment by cr4ckp0t** [comment]
I have no idea why you felt the need to open this. If the addon does not work for you, don't use it. You (or anyone) do not pay me to write any of the 20+ addon projects I have currently maintained on Twitch. Coupled with my actual life (wife, etc.) and ingame things (raiding, etc.) then I work on these projects as I am able and have time. 

Some of you guys seem to lose sight of the fact that addon developers do have lives and 99.9% of us do not get paid for what we do. I work on them as I have time/motivation.
