### ISSUE TITLE
Lua.error

### ISSUE THREAD

**Issue by llcor3ll** [cr4ckp0t/ElvUI_RaidMarkers#7]
Message: ...terface\AddOns\ElvUI\Modules\DataTexts\DataTexts.lua:756: Events must be registered as a table.
Time: Thu Jul 16 14:56:38 2020
Count: 1
Stack: ...terface\AddOns\ElvUI\Modules\DataTexts\DataTexts.lua:756: Events must be registered as a table.
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Modules\DataTexts\DataTexts.lua"]:756: in function `RegisterDatatext'
[string "@Interface\AddOns\ElvUI_RaidMarkers\Datatext.lua"]:130: in main chunk

Locals: (*temporary) = "Events must be registered as a table."

**Comment by cr4ckp0t** [comment]
Make sure you're updated to the latest version of ElvUI and this addon.
