### ISSUE TITLE
Addon still shows to be for game version 8.3.x instead of 9.0.1

### ISSUE THREAD

**Issue by Glowsome** [cr4ckp0t/ElvUI_RaidMarkers#9]
After latest update (6.0.1) ( in game version 9.0.1) the addon functions again, however if i look at twitch the Game version is still depicted as 8.3.0 .. 

- functionality-wise its ok, so i think we are just looking at a versioning issue.

**Comment by cr4ckp0t** [comment]
Please don't open tickets based on what the Twitch client is telling you. It's awful and completely screws up versioning. The TOC version in 6.0.1 is correct, and 6.0.2 will be for patch 9.0.2.
